version: '3.8'
services:
  # cowrie:
  #   image: cowrie/cowrie:latest
  #   container_name: cowrie
  #   ports:
  #     - "2222:2222"
  #     - "2223:2223"
  #   volumes:
  #     - cowrie-etc:/cowrie/cowrie-git/etc
  #     - cowrie-var:/cowrie/cowrie-git/var

  cowrie-db:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: mysql-cowrie
        restart: unless-stopped
        ports:
            - "3306:3306"
        volumes:
            - mysqldata:/var/lib/mysqldata
            - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
            # - ./docker/mysql.sql:/var/lib/mysqldata/mysql.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: "Asia/Jakarta"
volumes:
  # cowrie-etc:
  # cowrie-var:
  mysqldata: